name: Russian Flying Squirrel
favicon: null
layout_spectrum: 0.9138310577254742
typography_spectrum: 0.31515624769963324
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.08264795108698308
  lightness: 0.19787102355621755
  saturation: 0.5319380066357553
  rhythmicContrast: 0.13348575285635889
purpose: []
