name: Russian Flying Squirrel
favicon: null
layout_spectrum: 0.60614
typography_spectrum: 0.31515624769963324
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6f8f7'
    - '#8e5b96'
    - '#e3ca6e'
    - '#223829'
    - '#5b968a'
  brandStrength: 0.9375
  lightness: 0.19787102355621755
  saturation: 0.5319380066357553
  rhythmicContrast: 0.13348575285635889
purpose: []
